/**
 * effector_board — Daisy Seed main
 *
 * Wiring (Daisy Seed v1 pinout):
 *   Knob1 (ADC0 / pin 15) → Delay Time
 *   Knob2 (ADC1 / pin 16) → Delay Feedback
 *   Knob3 (ADC2 / pin 17) → Delay Mix
 *   Knob4 (ADC3 / pin 18) → Reverb Room
 *   Knob5 (ADC4 / pin 19) → Reverb Damping
 *   Knob6 (ADC5 / pin 20) → Reverb Mix
 *
 * Build: make daisy  (from project root)
 */

#include "daisy_seed.h"
#include "daisysp.h"

// Faust runtime base classes
#include "faust/dsp/dsp.h"
#include "faust/gui/UI.h"
#include "faust/gui/meta.h"
#include "faust/gui/MapUI.h"

// Generated by: make gen-daisy (faust -lang cpp, bare output)
#include "effector_board.h"

using namespace daisy;
using namespace daisysp;

// ----------------------------------------------------------------
// Hardware
// ----------------------------------------------------------------
static DaisySeed hw;

// Faust DSP in SDRAM (delay/reverb buffers exceed internal SRAM)
static mydsp DSY_SDRAM_BSS dsp;
static MapUI ui;
static FAUSTFLOAT knobs[6];

// ----------------------------------------------------------------
// Audio callback
// ----------------------------------------------------------------
void AudioCallback(AudioHandle::InputBuffer  in,
                   AudioHandle::OutputBuffer out,
                   size_t                    size)
{
    // Read knobs (0.0 – 1.0)
    for (int k = 0; k < 6; k++)
        knobs[k] = hw.adc.GetFloat(k);

    // --- Map knobs to Faust parameters via MapUI ---
    // Delay Time: 10 – 1000 ms
    ui.setParamValue("/effector_board/Delay/Time",
                     10.0f + knobs[0] * 990.0f);
    // Delay Feedback: 0 – 0.95
    ui.setParamValue("/effector_board/Delay/Feedback",
                     knobs[1] * 0.95f);
    // Delay Mix: 0 – 1
    ui.setParamValue("/effector_board/Delay/Mix",
                     knobs[2]);
    // Reverb Room: 0 – 1
    ui.setParamValue("/effector_board/Hall_Reverb/Room",
                     knobs[3]);
    // Reverb Damping: 0 – 1
    ui.setParamValue("/effector_board/Hall_Reverb/Damping",
                     knobs[4]);
    // Reverb Mix: 0 – 1
    ui.setParamValue("/effector_board/Hall_Reverb/Mix",
                     knobs[5]);

    // --- DSP compute ---
    // Faust expects float* arrays (non-interleaved)
    FAUSTFLOAT* inputs[1]  = { (FAUSTFLOAT*)in[0] };
    FAUSTFLOAT* outputs[2] = { out[0], out[1] };
    dsp.compute(static_cast<int>(size), inputs, outputs);
}

// ----------------------------------------------------------------
// main
// ----------------------------------------------------------------
int main()
{
    hw.Configure();
    hw.Init();
    hw.SetAudioBlockSize(48);

    // ADC config: 6 knobs
    AdcChannelConfig adc_cfg[6];
    adc_cfg[0].InitSingle(hw.GetPin(15));
    adc_cfg[1].InitSingle(hw.GetPin(16));
    adc_cfg[2].InitSingle(hw.GetPin(17));
    adc_cfg[3].InitSingle(hw.GetPin(18));
    adc_cfg[4].InitSingle(hw.GetPin(19));
    adc_cfg[5].InitSingle(hw.GetPin(20));
    hw.adc.Init(adc_cfg, 6);
    hw.adc.Start();

    // Faust DSP init + build parameter map
    dsp.init(static_cast<int>(hw.AudioSampleRate()));
    dsp.buildUserInterface(&ui);

    hw.StartAudio(AudioCallback);

    while (true)
    {
        // Main loop — nothing to do here (audio runs in callback)
        System::Delay(1);
    }
}
